# real_streams_generator.py
# ===============
# Generate ordered real-data streams and chunk-level proxy concept labels.

# This version avoids CSV outputs and keeps only the files needed for the
# pipeline:
# - ordered stream NPZ (X, y)
# - ordered metadata JSON
# - inspection JSON
# - baseline performance profiles NPZ
# - proxy concept labels NPY

# Proxy labels are derived from baseline classifier performance profiles,
# NOT from the meta-features under evaluation. This avoids circularity when
# comparing pymfe vs ABFS-based meta-features.

# Output files generated by this script
# ====================================

# For a dataset name like `elec2` and output_dir like `real_streams_out/`,
# the script writes the following files:

# 1) elec2_ordered.npz
#    - Raw ordered stream in NumPy format.
#    - Contains:
#        X = feature matrix of the ordered stream
#        y = original class labels
#    - This is the main file used later for chunking and meta-feature extraction.

# 2) elec2_ordered_meta.json
#    - Pipeline metadata / reproducibility file.
#    - Stores:
#        dataset name
#        chunk size
#        number of chunks
#        number of proxy concepts
#        feature names
#        categorical feature indices
#        paths to output files
#    - Use this to reproduce the exact stream-generation setup.

# 3) elec2_inspection.json
#    - Dataset summary / descriptive statistics.
#    - Stores:
#        number of instances
#        number of features
#        numeric/categorical feature counts
#        class distribution
#        imbalance ratio
#        missing-value statistics
#        number of chunks
#        proxy-label distribution
#    - Use this for dataset inspection and reporting.

# 4) elec2_baseline_profiles.npz
#    - Chunk-level baseline performance profiles.
#    - Contains the performance vectors produced by the baseline classifiers
#      (GNB, KNN, HT) on the raw ordered stream.
#    - Used internally to construct proxy concept labels.
#    - Optional for downstream use; mainly useful for debugging and analysis.

# 5) elec2_proxy_labels.npy
#    - Chunk-level proxy concept labels.
#    - This is the target vector y_proxy for the meta-feature classification task.
#    - It is derived from the baseline performance profiles and is independent
#      of the meta-features under evaluation


import os
import json
import warnings

import numpy as np
import pandas as pd
from river import datasets, naive_bayes, neighbors, tree
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")



# ============================================================
# EXPERIMENT CONFIGURATION
# ============================================================

DATASET_NAME = "elec2"
OUTPUT_DIR = "real_streams_data"
MAX_ROWS = 50000
CHUNK_SIZE = 300
N_PROXY_CONCEPTS = 4
RANDOM_STATE = 42
INSPECT_ONLY = False



DATASET_REGISTRY = {
    "elec2": datasets.Elec2(),
    "airlines": datasets.Airlines(),
    "covtype": datasets.Covtype(),
    "phishing": datasets.Phishing(),
    "http": datasets.HTTP(),
}



def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def load_river_dataset(name: str, max_rows=None) -> pd.DataFrame:
    name = name.lower()
    if name not in DATASET_REGISTRY:
        raise ValueError(f"Unknown dataset '{name}'. Available: {list(DATASET_REGISTRY.keys())}")

    rows = []
    for i, (x, y) in enumerate(DATASET_REGISTRY[name]):
        row = dict(x)
        row["target"] = y
        row["t"] = i
        rows.append(row)
        if max_rows is not None and len(rows) >= max_rows:
            break

    df = pd.DataFrame(rows)
    if "target" not in df.columns:
        raise ValueError("The loaded dataset did not produce a target column.")
    return df


def basic_cleaning(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for col in df.columns:
        if col in ["target", "t", "window_id"]:
            continue
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())
        else:
            if not df[col].mode().empty:
                df[col] = df[col].fillna(df[col].mode().iloc[0])
            else:
                df[col] = df[col].fillna("missing")

    if df["target"].isna().any():
        if not df["target"].mode().empty:
            df["target"] = df["target"].fillna(df["target"].mode().iloc[0])
        else:
            df["target"] = df["target"].fillna(0)
    return df


def add_window_id(df: pd.DataFrame, window_size: int) -> pd.DataFrame:
    df = df.copy().reset_index(drop=True)
    df["window_id"] = df.index // window_size
    return df


def encode_for_abfs(df: pd.DataFrame):
    df = df.copy()
    drop_cols = [c for c in ["target", "t", "window_id"] if c in df.columns]
    X_df = df.drop(columns=drop_cols)

    encoded_cols = []
    feature_names = []
    categorical_indices = []

    for idx, col in enumerate(X_df.columns):
        s = X_df[col]
        feature_names.append(col)
        if pd.api.types.is_numeric_dtype(s):
            encoded_cols.append(s.astype(float))
        else:
            cat = s.astype("category")
            encoded_cols.append(cat.cat.codes.astype(float))
            categorical_indices.append(idx)

    if not encoded_cols:
        raise ValueError("No feature columns found after dropping helper columns.")

    X_encoded = pd.concat(encoded_cols, axis=1)
    X_encoded.columns = feature_names
    y = df["target"].values
    return X_encoded, y, feature_names, categorical_indices


def df_to_xy(df: pd.DataFrame):
    X_df, y, feature_names, categorical_indices = encode_for_abfs(df)
    X = X_df.values.astype(float)
    return X, y, feature_names, categorical_indices


def make_ordered_stream(df: pd.DataFrame, chunk_size: int = 200) -> pd.DataFrame:
    return add_window_id(df, chunk_size)


def make_chunked_stream(df: pd.DataFrame, chunk_size: int = 200):
    df = add_window_id(df, chunk_size)
    chunks = []
    for wid in sorted(df["window_id"].unique()):
        chunk = df[df["window_id"] == wid].copy().reset_index(drop=True)
        chunks.append(chunk)
    return chunks


def _make_baseline_clfs():
    return {
        "GNB": naive_bayes.GaussianNB(),
        "KNN": neighbors.KNNClassifier(),
        "HT": tree.HoeffdingTreeClassifier(),
    }


def _safe_pred_proba(model, x_dict):
    if hasattr(model, "predict_proba_one"):
        proba = model.predict_proba_one(x_dict)
        if proba is None:
            return np.nan
        return proba
    return None


def _chunk_performance_profiles(X: np.ndarray, y: np.ndarray, chunk_size: int):
    clfs = _make_baseline_clfs()
    classes = list(np.unique(y))
    n_chunks = int(np.ceil(len(X) / chunk_size))
    profiles = []

    for chunk_id in range(n_chunks):
        start = chunk_id * chunk_size
        end = min((chunk_id + 1) * chunk_size, len(X))
        if start >= end:
            break

        chunk_stats = []
        for _, clf in clfs.items():
            correct = 0
            total = 0
            true_prob_sum = 0.0
            loss_sum = 0.0
            n_prob = 0

            for i in range(start, end):
                x_dict = {j: float(X[i, j]) for j in range(X.shape[1])}
                y_true = y[i]
                y_pred = clf.predict_one(x_dict)
                if y_pred is None:
                    y_pred = classes[0]

                correct += int(y_pred == y_true)
                total += 1
                loss_sum += float(y_pred != y_true)

                proba = _safe_pred_proba(clf, x_dict)
                if isinstance(proba, dict):
                    true_prob_sum += float(proba.get(y_true, 0.0))
                    n_prob += 1

                clf.learn_one(x_dict, y_true)

            acc = correct / max(total, 1)
            mean_loss = loss_sum / max(total, 1)
            mean_true_prob = true_prob_sum / max(n_prob, 1) if n_prob > 0 else np.nan
            chunk_stats.extend([acc, mean_loss, mean_true_prob])

        profiles.append(chunk_stats)

    return np.asarray(profiles, dtype=float), list(clfs.keys())


def _impute_nan_with_colmean(A: np.ndarray) -> np.ndarray:
    A = A.copy().astype(float)
    for j in range(A.shape[1]):
        col = A[:, j]
        mask = np.isnan(col)
        if np.any(~mask):
            col_mean = np.nanmean(col)
        else:
            col_mean = 0.0
        col[mask] = col_mean
        A[:, j] = col
    return A


def _remap_labels_by_first_occurrence(labels: np.ndarray) -> np.ndarray:
    mapping = {}
    next_id = 0
    remapped = []
    for l in labels:
        if l not in mapping:
            mapping[l] = next_id
            next_id += 1
        remapped.append(mapping[l])
    return np.asarray(remapped, dtype=int)


def assign_proxy_concept_labels(performance_profiles: np.ndarray, n_proxy_concepts: int = 4, random_state: int = 42):
    if len(performance_profiles) == 0:
        return np.asarray([], dtype=int), None

    X = _impute_nan_with_colmean(performance_profiles)
    Xs = StandardScaler().fit_transform(X)
    k = int(max(2, min(n_proxy_concepts, len(Xs))))
    km = KMeans(n_clusters=k, random_state=random_state, n_init=20)
    raw_labels = km.fit_predict(Xs)
    proxy_labels = _remap_labels_by_first_occurrence(raw_labels)
    return proxy_labels, km


def summarize_dataset(df: pd.DataFrame, dataset_name: str, chunk_size: int = 200):
    X, y, feature_names, categorical_indices = df_to_xy(df)
    missing_per_col = df.isna().sum().to_dict()
    total_missing = int(df.isna().sum().sum())

    y_values, y_counts = np.unique(y, return_counts=True)
    class_dist = {str(k): int(v) for k, v in zip(y_values, y_counts)}
    majority_class_count = int(y_counts.max())
    minority_class_count = int(y_counts.min())
    imbalance_ratio = float(majority_class_count / max(1, minority_class_count))

    n_instances = int(len(df))
    n_chunks = int(np.ceil(n_instances / chunk_size))
    n_total_features = int(X.shape[1])
    n_categorical = int(len(categorical_indices))
    n_numeric = n_total_features - n_categorical

    return {
        "dataset": dataset_name,
        "n_instances": n_instances,
        "n_features": n_total_features,
        "n_numeric_features": n_numeric,
        "n_categorical_features": n_categorical,
        "categorical_indices": categorical_indices,
        "class_distribution": class_dist,
        "imbalance_ratio": imbalance_ratio,
        "n_missing_values_total": total_missing,
        "missing_values_per_column": {str(k): int(v) for k, v in missing_per_col.items()},
        "chunk_size": int(chunk_size),
        "n_chunks": n_chunks,
        "feature_names": feature_names,
    }


def print_summary(summary: dict):
    print("\n" + "=" * 72)
    print(f"Dataset: {summary['dataset']}")
    print("=" * 72)
    print(f"Instances               : {summary['n_instances']}")
    print(f"Features                : {summary['n_features']}")
    print(f"Numeric features         : {summary['n_numeric_features']}")
    print(f"Categorical features     : {summary['n_categorical_features']}")
    print(f"Chunk size               : {summary['chunk_size']}")
    print(f"Number of chunks         : {summary['n_chunks']}")
    print(f"Total missing values     : {summary['n_missing_values_total']}")
    print(f"Imbalance ratio          : {summary['imbalance_ratio']:.4f}")
    print(f"Class distribution       : {summary['class_distribution']}")
    print(f"Categorical indices      : {summary['categorical_indices']}")
    print("=" * 72 + "\n")


def save_npz(path: str, **arrays):
    ensure_dir(os.path.dirname(path))
    np.savez(path, **arrays)


def save_metadata(path: str, metadata: dict):
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)



def generate_real_streams(dataset_name: str, output_dir: str, max_rows=None, chunk_size: int = 200, n_proxy_concepts: int = 4, random_state: int = 42):
    ensure_dir(output_dir)

    df = load_river_dataset(dataset_name, max_rows=max_rows)
    df = basic_cleaning(df)
    ordered_df = make_ordered_stream(df, chunk_size=chunk_size)
    X, y, feature_names, categorical_indices = df_to_xy(ordered_df)

    ordered_npz_path = os.path.join(output_dir, f"{dataset_name}_ordered.npz")
    ordered_meta_path = os.path.join(output_dir, f"{dataset_name}_ordered_meta.json")
    inspection_path = os.path.join(output_dir, f"{dataset_name}_inspection.json")
    profiles_npz_path = os.path.join(output_dir, f"{dataset_name}_baseline_profiles.npz")
    proxy_labels_path = os.path.join(output_dir, f"{dataset_name}_proxy_labels.npy")


    save_npz(ordered_npz_path, X=X, y=y)

    chunks = make_chunked_stream(df, chunk_size=chunk_size)

    performance_profiles, clf_names = _chunk_performance_profiles(X, y, chunk_size=chunk_size)
    proxy_labels, _ = assign_proxy_concept_labels(performance_profiles, n_proxy_concepts=n_proxy_concepts, random_state=random_state)
    save_npz(profiles_npz_path, performance_profiles=performance_profiles)
    np.save(proxy_labels_path, proxy_labels)

    metadata = {
        "dataset": dataset_name,
        "variant": "ordered",
        "source": "river",
        "n_instances": int(len(ordered_df)),
        "n_features": int(X.shape[1]),
        "feature_names": feature_names,
        "categorical_indices": categorical_indices,
        "chunk_size": int(chunk_size),
        "n_chunks": int(len(chunks)),
        "max_rows": None if max_rows is None else int(max_rows),
        "n_proxy_concepts": int(n_proxy_concepts),
        "proxy_label_source": "baseline classifier performance profiles clustered with KMeans",
        "proxy_label_independent_of_meta_features": True,
        "baseline_classifiers": list(clf_names),
        "output_files": {
            "ordered_npz": ordered_npz_path,
            "ordered_meta": ordered_meta_path,
            "inspection": inspection_path,
            "baseline_profiles_npz": profiles_npz_path,
            "proxy_labels_npy": proxy_labels_path,
        },
    }
    save_metadata(ordered_meta_path, metadata)

    inspection = summarize_dataset(ordered_df, dataset_name, chunk_size=chunk_size)
    inspection["n_proxy_concepts"] = int(n_proxy_concepts)
    inspection["proxy_label_source"] = "baseline classifier performance profiles clustered with KMeans"
    inspection["baseline_classifiers"] = list(clf_names)
    inspection["proxy_label_distribution"] = {str(k): int(v) for k, v in zip(*np.unique(proxy_labels, return_counts=True))}
    save_metadata(inspection_path, inspection)
    print_summary(inspection)

    return {
        "df": ordered_df,
        "X": X,
        "y": y,
        "feature_names": feature_names,
        "categorical_indices": categorical_indices,
        "chunks": chunks,
        "performance_profiles": performance_profiles,
        "proxy_labels": proxy_labels,
        "metadata_path": ordered_meta_path,
        "inspection_path": inspection_path,
        "baseline_profiles_npz": profiles_npz_path,
        "proxy_labels_path": proxy_labels_path,
        "ordered_npz_path": ordered_npz_path,
    }


def get_stream_xy(dataset_name: str, max_rows=None):
    df = load_river_dataset(dataset_name, max_rows=max_rows)
    df = basic_cleaning(df)
    X, y, feature_names, categorical_indices = df_to_xy(df)
    return X, y, feature_names, categorical_indices


def get_chunked_stream(dataset_name: str, max_rows=None, chunk_size: int = 200):
    df = load_river_dataset(dataset_name, max_rows=max_rows)
    df = basic_cleaning(df)
    chunks = make_chunked_stream(df, chunk_size=chunk_size)
    for chunk in chunks:
        X, y, feature_names, categorical_indices = df_to_xy(chunk)
        yield X, y, chunk, feature_names, categorical_indices


def load_proxy_labels(path: str):
    return np.load(path)



def main():

    df = load_river_dataset(DATASET_NAME, max_rows=MAX_ROWS)
    df = basic_cleaning(df)
    ordered_df = make_ordered_stream(df, chunk_size=CHUNK_SIZE)

    inspection = summarize_dataset(ordered_df, DATASET_NAME, chunk_size=CHUNK_SIZE)
    print_summary(inspection)

    if INSPECT_ONLY:
        return

    generate_real_streams(
        dataset_name=DATASET_NAME,
        output_dir=OUTPUT_DIR,
        max_rows=MAX_ROWS,
        chunk_size=CHUNK_SIZE,
        n_proxy_concepts=N_PROXY_CONCEPTS,
        random_state=RANDOM_STATE,
    )


if __name__ == "__main__":
    main()
